Верстка главной страницы
htmlacademy-adaptive/209146-cat-energy-25 pull request #2
Opened 2022-04-03 19:28 UTC by slipnir

2022-04-04 18:40 UTC, costigans requested changes

2022-04-04 18:40 UTC, costigans commented on source/index.html
> +        <img src="" alt="">
Не оставляй `img` пустыми, ты уже знаешь размер и имена фалов

2022-04-04 18:40 UTC, costigans commented on source/index.html
> +      </div>
Для чего эти «обёртки»?

2022-04-04 18:40 UTC, costigans commented on source/index.html
> +      <div class="header__menu menu">
Тоже лишняя обёртка, `ul` уже выполняет «объединяющую» функцию, сейчас его достаточно

2022-04-04 18:40 UTC, costigans commented on source/index.html
> +        <div class="banner__img"></div>
Это не `div`

2022-04-04 18:40 UTC, costigans commented on source/index.html
> +              <div class="card__icon">
Лишняя обёртка

2022-04-04 18:40 UTC, costigans commented on source/index.html
> +              <div class="card__title">Похудение</div>
Простого `div` достаточно?

2022-04-04 18:40 UTC, costigans commented on source/index.html
> +          <div class="info__icon"></div>
Не `div`

2022-04-04 18:40 UTC, costigans commented on source/index.html
> +        <p class="contacts__text">ул. Большая Конюшенная, д. 19/8 Санкт-Петербург</p>
Под адрес существует специальный тег

2022-04-04 18:40 UTC, costigans commented on source/index.html
> +        <div class="footer__icon"></div>
Это ссылки

2022-04-04 18:40 UTC, costigans commented on source/index.html
> +        <img class="agency__img" src="" alt="">
Сверься с ТЗ, что из этого ссылка

2022-04-05 12:55 UTC, slipnir commented on source/index.html
> +              <div class="card__icon">
вот тут не пойму почему лишняя обертка

у меня есть `<div class="banner__cards cards">` - это общий контейнер, объединяющий 2 карточки, внутри него будут позиционироваться блоки

есть `<div class="cards__card card">` - это контейнер одной карточки, внутри которого будут позиционироваться элементы непосредственно карточки

если убрать одну обертку, то получится что мои карточки развалятся на 4 блочка

2022-04-05 12:57 UTC, slipnir commented on source/index.html
> +        <img class="agency__img" src="" alt="">
а где ТЗ?) я просмотрел материалы для домашнего задания и ничего не нашел

2022-04-05 13:00 UTC, costigans commented on source/index.html
> +              <div class="card__icon">
Я про 34 строчку :)
`Img` достаточно

2022-04-05 13:00 UTC, costigans commented on source/index.html
> +        <img class="agency__img" src="" alt="">
https://up.htmlacademy.ru/adaptive/25/project/cat-energy#specification

2022-04-05 20:39 UTC, costigans requested changes

2022-04-05 20:39 UTC, costigans commented on source/index.html
> +        <a href="" class="footer__icon"></a>
А почему пустые?

2026-05-07 07:14 UTC, closed without merging